using System.Net;
using System.Text;

namespace JobRadar;

/// <summary>
/// Generates a clean one-page CV/profile PDF from a <see cref="UserProfile"/>, reusing the same
/// HTML→PDF path as the job reports (Edge headless). First step of "CV Studio" — it renders what
/// the profile knows today (summary, skills, languages, target roles); detailed work history will
/// come once LinkedIn/GitHub import lands.
/// </summary>
public static class CvPdf
{
    /// <summary>Builds the CV as a self-contained HTML document.</summary>
    public static string BuildHtml(UserProfile p)
    {
        string E(string? s) => WebUtility.HtmlEncode(s ?? "");
        string role = string.IsNullOrWhiteSpace(p.Field) ? "Professional Profile" : p.Field;

        var contact = new List<string>();
        if (p.Locations.Count > 0) contact.Add(string.Join(" · ", p.Locations));
        var modes = new List<string>();
        if (p.Remote) modes.Add("Remote");
        if (p.Hybrid) modes.Add("Hybrid");
        if (p.Onsite) modes.Add("On-site");
        if (modes.Count > 0) contact.Add(string.Join(" / ", modes));

        var sb = new StringBuilder();
        sb.Append($@"<!doctype html><html lang=""en""><head><meta charset=""utf-8""><title>{E(p.Name)} — CV</title>
<style>
:root{{--ink:#1c1b22;--muted:#5c6370;--accent:#4C2DBE;--accent2:#ECE9FB;--line:#e4e2ec;
--sans:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;--mono:'Cascadia Code',Consolas,monospace;}}
*{{box-sizing:border-box;}}body{{margin:0;color:var(--ink);font-family:var(--sans);line-height:1.5;font-size:13px;background:#fff;}}
.page{{max-width:820px;margin:0 auto;padding:40px 46px;}}
header{{border-bottom:3px solid var(--accent);padding-bottom:14px;}}
h1{{font-size:30px;margin:0;letter-spacing:-.02em;font-weight:800;}}
.role{{font-size:14px;color:var(--accent);font-weight:600;margin-top:3px;}}
.contact{{font-family:var(--mono);font-size:10.5px;color:var(--muted);margin-top:7px;}}
section{{margin-top:22px;}}
h2{{font-family:var(--mono);font-size:11px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:var(--accent);margin:0 0 9px;}}
.summary{{font-size:13px;color:#33323b;}}
.two{{display:grid;grid-template-columns:1.5fr 1fr;gap:34px;}}
.skillrow{{display:flex;gap:8px;font-size:12.5px;margin-bottom:4px;}}
.tag{{display:inline-block;background:var(--accent2);color:var(--accent);border-radius:7px;padding:2px 9px;font-size:11px;font-family:var(--mono);margin:0 5px 5px 0;}}
.core{{font-weight:600;color:var(--ink);}}
.muted{{color:var(--muted);font-size:12px;}}
ul{{margin:6px 0 0;padding-left:18px;}}li{{margin-bottom:3px;color:#3c3a4b;}}
.foot{{margin-top:26px;padding-top:10px;border-top:1px solid var(--line);font-family:var(--mono);font-size:9.5px;color:var(--muted);}}
@media print{{@page{{size:A4;margin:0;}}body{{-webkit-print-color-adjust:exact;print-color-adjust:exact;}}}}
</style></head><body><div class=""page"">

<header>
  <h1>{E(p.Name)}</h1>
  <div class=""role"">{E(role)}</div>
  <div class=""contact"">{E(string.Join("  ·  ", contact))}</div>
</header>");

        if (!string.IsNullOrWhiteSpace(p.Summary))
            sb.Append($@"<section><h2>Summary</h2><p class=""summary"">{E(p.Summary)}</p></section>");

        sb.Append(@"<div class=""two""><div>");

        if (p.CoreSkills.Count > 0)
        {
            sb.Append(@"<section><h2>Core skills</h2>");
            foreach (var s in p.CoreSkills) sb.Append($@"<div class=""skillrow""><span class=""core"">▹ {E(s)}</span></div>");
            sb.Append("</section>");
        }

        // We don't have structured work history yet — show experience level + target roles instead.
        sb.Append(@"<section><h2>Experience</h2>");
        sb.Append($@"<p class=""muted"">~{p.YearsExperience} years of experience · target level: {E(p.SeniorityTarget)}</p>");
        if (p.JobTitles.Count > 0)
        {
            sb.Append(@"<p class=""muted"" style=""margin-top:6px;"">Target roles:</p><ul>");
            foreach (var t in p.JobTitles) sb.Append($"<li>{E(t)}</li>");
            sb.Append("</ul>");
        }
        sb.Append("</section>");

        sb.Append(@"</div><div>");

        if (p.Skills.Count > 0)
        {
            sb.Append(@"<section><h2>Skills &amp; tools</h2>");
            foreach (var s in p.Skills) sb.Append($@"<span class=""tag"">{E(s)}</span>");
            sb.Append("</section>");
        }

        if (p.Languages.Count > 0)
        {
            sb.Append(@"<section><h2>Languages</h2><div class=""muted"">");
            sb.Append(E(string.Join(" · ", p.Languages)));
            sb.Append("</div></section>");
        }

        sb.Append(@"</div></div>");
        sb.Append(@"<div class=""foot"">Generated by Job Radar from the candidate profile.</div>");
        sb.Append(@"</div></body></html>");
        return sb.ToString();
    }

    /// <summary>Writes the CV to <paramref name="outDir"/> as HTML and (if Edge is available) PDF.
    /// Returns the path to open (PDF when produced, otherwise the HTML), or null on failure.</summary>
    public static string? Export(UserProfile p, string outDir, string stamp)
    {
        try
        {
            Directory.CreateDirectory(outDir);
            string safeName = string.Concat((string.IsNullOrWhiteSpace(p.Name) ? "CV" : p.Name)
                .Split(Path.GetInvalidFileNameChars())).Replace(' ', '_');
            string html = Path.Combine(outDir, $"{safeName}-CV-{stamp}.html");
            string pdf = Path.Combine(outDir, $"{safeName}-CV-{stamp}.pdf");
            File.WriteAllText(html, BuildHtml(p), new UTF8Encoding(false));

            string? edge = Reports.FindEdge();
            if (edge is not null && Reports.WritePdf(html, pdf, edge) && File.Exists(pdf))
                return pdf;
            return html; // Edge missing — at least hand back the HTML
        }
        catch { return null; }
    }
}
