namespace JobRadar;

/// <summary>PT (default) and EN string tables used by <see cref="Loc"/>. Keys are section.element.</summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> Pt = new()
    {
        // nav
        ["nav.home"] = "Início",
        ["nav.profile"] = "Perfil",
        ["nav.jobs"] = "Vagas",
        ["nav.improve"] = "Evoluir",
        ["nav.settings"] = "Definições",
        ["theme.toggle"] = "Tema: {0}",

        // home
        ["home.tagline"] = "Dá o teu CV — a IA monta o teu perfil e encontramos as vagas que encaixam, pontuadas e explicadas. Tudo local, com o teu Claude CLI ou um modelo local (BYOK).",
        ["home.search"] = "Procurar vagas",
        ["home.search.tip"] = "Recolhe das fontes e classifica de novo",
        ["home.viewJobs"] = "Ver vagas",
        ["home.viewJobs.tip"] = "Mostra as vagas já guardadas, sem nova pesquisa",
        ["home.editProfile"] = "Ver / editar perfil",
        ["home.loadOtherCv"] = "Carregar outro CV",
        ["home.firstTitle"] = "Começa pelo teu CV",
        ["home.firstSub"] = "PDF de texto. A IA extrai o perfil e tu confirmas antes de procurar.",
        ["home.pickCv"] = "Escolher CV (PDF)…",
        ["home.demoCv"] = "Usar CV de exemplo",
        ["home.demoCv.tip"] = "Carrega o perfil de exemplo (John Doe) — sem tokens, não mexe no teu perfil.",
        ["home.demoRun"] = "Ver demonstração (sem IA)",
        ["home.privacy"] = "Privado e local. A leitura do CV e a pontuação usam o teu Claude CLI ou um modelo local (BYOK) — nada é enviado para servidores. A demonstração e o CV de exemplo não gastam tokens.",

        // profile
        ["profile.title"] = "O teu perfil",
        ["profile.sub"] = "Confirma o que a IA extraiu e responde ao que um CV não diz.",
        ["profile.name"] = "NOME",
        ["profile.field"] = "ÁREA / PROFISSÃO",
        ["profile.field.wm"] = "Software Engineering, Enfermagem, Contabilidade…",
        ["profile.titles"] = "TÍTULOS DE CARGO (pesquisa, vírgulas)",
        ["profile.titles.wm"] = "Backend Developer, Software Engineer",
        ["profile.coreSkills"] = "COMPETÊNCIAS-CHAVE (vírgulas)",
        ["profile.otherSkills"] = "OUTRAS SKILLS",
        ["profile.locations"] = "LOCALIZAÇÕES",
        ["profile.years"] = "ANOS DE EXPERIÊNCIA",
        ["profile.seniority"] = "NÍVEL-ALVO",
        ["profile.salary"] = "SALÁRIO €/ANO (mín / alvo)",
        ["profile.salary.min"] = "mínimo",
        ["profile.salary.target"] = "alvo",
        ["profile.workmode"] = "MODO DE TRABALHO",
        ["profile.remote"] = "Remoto",
        ["profile.hybrid"] = "Híbrido",
        ["profile.onsite"] = "Presencial",
        ["profile.summary"] = "RESUMO",
        ["profile.classification"] = "CLASSIFICAÇÃO",
        ["profile.classHint"] = "IA = 0–100 com justificação. Keywords = rápido, sem IA.",
        ["profile.genCv"] = "Gerar CV (PDF)",
        ["profile.genCv.tip"] = "Gera um CV em PDF a partir deste perfil",
        ["profile.reset"] = "Recomeçar",

        // results
        ["results.of"] = " de ",
        ["results.search.wm"] = "Pesquisar nas vagas…",
        ["results.filter"] = "Filtro",
        ["results.filter.tip"] = "Adicionar um filtro (ex.: descrição contém C#)",
        ["results.minScore"] = "Score mín.",
        ["results.rescore"] = "Reclassificar",
        ["results.rescore.tip"] = "Volta a pontuar com o modelo das Definições",
        ["results.export"] = "Exportar",
        ["results.linkedin.tip"] = "Abre o LinkedIn Jobs com a tua pesquisa",
        ["filter.remove.tip"] = "Remover filtro",
        ["results.howScore"] = "Como é calculado o score?",
        ["results.howScore.body"] = "1) Um filtro por palavras-chave do teu perfil dá um pré-score (competências-chave, modo de trabalho, localização, salário). 2) Em modo IA, as melhores são avaliadas 0–100 pelo modelo, com veredicto, razões e red-flags. Abre cada vaga para a lógica exata; clica no título para abrir o anúncio.",
        ["job.openTip"] = "Abrir o anúncio",
        ["job.why"] = "Porquê este score",
        ["job.openJob"] = "Abrir vaga",
        ["job.research"] = "Pesquisar empresa",
        ["job.research.tip"] = "Procura reviews e salários comparáveis na web e resume com o teu modelo",
        ["job.researching"] = "A pesquisar a empresa…",
        ["brief.reputation"] = "REPUTAÇÃO",
        ["brief.salary"] = "SALÁRIO",
        ["brief.expectation"] = "EXPECTATIVA SALARIAL PARA TI",
        ["common.sources"] = "FONTES",

        // improve
        ["improve.sub"] = "Um plano de carreira a partir do teu perfil e do mercado que o radar já viu — com pesquisa e fontes.",
        ["improve.intro"] = "O Radar pesquisa competências em procura, trajetória salarial e tendências de contratação para a tua área, cruza tudo com o teu perfil e as vagas já pontuadas, e devolve pontos fortes, lacunas a fechar, papéis-alvo e próximos passos — com fontes.",
        ["improve.generate"] = "Gerar plano de carreira",
        ["improve.byok"] = "Usa o teu motor de IA (Claude CLI ou modelo local) + pesquisa web key-free. Não gasta créditos pagos.",
        ["improve.positioning"] = "O TEU POSICIONAMENTO",
        ["improve.regenerate"] = "Regenerar",
        ["improve.regenerate.tip"] = "Voltar a pesquisar e regenerar o plano.",
        ["improve.strengths"] = "PONTOS FORTES",
        ["improve.gaps"] = "LACUNAS A FECHAR",
        ["improve.roles"] = "PAPÉIS-ALVO",
        ["improve.salaryTraj"] = "TRAJETÓRIA SALARIAL",
        ["improve.now"] = "AGORA",
        ["improve.potential"] = "POTENCIAL · 12–24 MESES",
        ["improve.steps"] = "PRÓXIMOS PASSOS",
        ["improve.signals"] = "SINAIS DO MERCADO",

        // settings
        ["settings.sub"] = "Aparência e motor de IA usado para ler o CV e pontuar as vagas.",
        ["settings.appearance"] = "ASPETO",
        ["settings.appearance.hint"] = "Claro, escuro ou a seguir o sistema.",
        ["settings.textsize"] = "TAMANHO DO TEXTO",
        ["settings.textsize.hint"] = "Aumenta a app inteira. Também com Ctrl +/− · Ctrl 0 · Ctrl+roda do rato.",
        ["settings.language"] = "IDIOMA",
        ["settings.language.hint"] = "Idioma da aplicação.",
        ["settings.aiEngine"] = "MOTOR DE IA",
        ["settings.aiEngine.hint"] = "Claude CLI usa a tua subscrição (BYOK). Modelo local usa um runtime compatível com OpenAI (LM Studio, Ollama, llama.cpp) — corre offline, sem subscrição.",
        ["settings.localModel"] = "Modelo local",
        ["settings.presets"] = "Presets:",
        ["settings.apiKey"] = "API KEY (opcional)",
        ["settings.claudeExe"] = "EXECUTÁVEL CLAUDE (PATH)",
        ["settings.model"] = "MODELO",
        ["settings.load"] = "Carregar",
        ["settings.model.hint"] = "Carrega a lista a partir do runtime local (tem de estar a correr no Base URL).",
        ["settings.on"] = "Ligado",
        ["settings.off"] = "Desligado",
        ["settings.apify.warnBold"] = "Atenção — custos: ",
        ["settings.apify.warn"] = "o Apify é pago e cada pesquisa consome créditos da tua conta Apify. Com o Apify ligado, a app pede sempre confirmação antes de procurar.",
        ["settings.apify.test"] = "Testar / procurar",
        ["settings.apify.test.tip"] = "Valida o token (grátis, sem créditos) e procura actors de LinkedIn",
        ["settings.apify.max"] = "MÁX. RESULTADOS (limita o custo)",
        ["settings.apify.hint"] = "Cola o token (apify.com → Settings → API) e carrega em “Testar / procurar”. Validar e listar é grátis; só a pesquisa em si consome créditos.",
        ["settings.save"] = "Guardar",

        // JSearch connector
        ["settings.jsearch"] = "JSEARCH (RAPIDAPI)",
        ["settings.jsearch.key"] = "RAPIDAPI KEY",
        ["settings.jsearch.max"] = "MÁX. RESULTADOS",
        ["settings.jsearch.warn"] = "o JSearch (RapidAPI) tem um tier gratuito com limite de pedidos por mês. Com o JSearch ligado, a app pede confirmação antes de procurar.",
        ["settings.jsearch.hint"] = "Cria conta no RapidAPI, subscreve o JSearch e copia a tua X-RapidAPI-Key.",
        ["jsearch.fetching"] = "A obter vagas do JSearch (RapidAPI)…",
        ["jsearch.count"] = "JSearch: {0} vagas.",
        ["jsearch.failed"] = "JSearch falhou (HTTP {0}) — verifica a chave RapidAPI.",
        ["jsearch.error"] = "JSearch: erro — {0}",

        // local model download (Ollama)
        ["settings.downloadModel"] = "DESCARREGAR MODELO (OLLAMA)",
        ["settings.downloadModel.wm"] = "ex.: llama3.2",
        ["settings.download"] = "Descarregar",
        ["settings.downloadModel.hint"] = "Descarrega um modelo via Ollama (tem de estar a correr no Base URL). LM Studio: usa a app do LM Studio.",
        ["models.pulling"] = "A descarregar {0} — {1}",
        ["models.pullDone"] = "{0} descarregado.",
        ["models.pullFail"] = "Falha ao descarregar — o Ollama está a correr no Base URL?",
        ["models.section"] = "MODELOS LOCAIS (OLLAMA)",
        ["models.none"] = "Ainda não tens modelos. Instala um abaixo (sugeridos) ou escreve o nome.",
        ["models.unreachable"] = "O Ollama não está a responder. Instala-o e mantém-no aberto.",
        ["models.active"] = "ativo",
        ["models.install"] = "Instalar modelo",
        ["models.suggested"] = "Sugeridos",
        ["models.refresh"] = "Atualizar",
        ["models.remove"] = "Remover",
        ["models.remove.tip"] = "Remover modelo",
        ["models.removeConfirm"] = "Remover {0}?",
        ["models.removeBody"] = "O modelo será apagado do teu disco.",
        ["models.getOllama"] = "Instalar o Ollama",
        ["models.setActive.tip"] = "Usar este modelo",
        ["connector.free"] = "Grátis",
        ["connector.paid"] = "Pago",
        ["connector.getKey"] = "Obter chave →",
        ["settings.advanced"] = "AVANÇADO",
        ["research.noWeb"] = "Sem resultados da pesquisa web (pode estar limitada — tenta de novo).",
        ["research.noModel"] = "O modelo não respondeu",
        ["research.failed"] = "Falhou a pesquisa da empresa.",
        ["usage.section"] = "USO E LIMITES",
        ["usage.refresh"] = "Atualizar",
        ["usage.hint"] = "Limites das APIs pagas/com quota. O teu Claude/modelo local não é medido aqui.",
        ["usage.jsearch"] = "{0} de {1} pedidos restantes este mês",
        ["usage.jsearch.none"] = "faz uma pesquisa com o JSearch para ver a quota",
        ["usage.claude"] = "subscrição (não medido aqui) — se atingires o limite, a pesquisa/pontuação falha",
        ["usage.local"] = "local — sem limites",
        ["usage.unknown"] = "—",

        // sources & keys setup guide
        ["settings.sources"] = "FONTES E CHAVES",
        ["setup.jsearch"] = "JSearch (RapidAPI) — agregador de vagas. Subscreve e copia a X-RapidAPI-Key.",
        ["setup.apify"] = "Apify — conector LinkedIn (pago). Cria um token de API.",
        ["setup.ollama"] = "Ollama — modelos locais. Instala e descarrega modelos.",
        ["setup.lmstudio"] = "LM Studio — modelos locais com interface gráfica.",
        ["setup.open"] = "Abrir",
        ["setup.library"] = "Modelos",

        // about / update
        ["settings.about"] = "SOBRE",
        ["settings.version"] = "Versão {0}",
        ["settings.checkUpdate"] = "Procurar atualizações",
        ["update.checking"] = "A procurar atualizações…",
        ["update.upToDate"] = "Estás na última versão ({0}).",
        ["update.available"] = "Nova versão disponível: {0}",
        ["update.downloading"] = "A descarregar atualização — {0}",
        ["update.failed"] = "Não consegui verificar/descarregar. Tenta a página de download.",
        ["update.openPage"] = "Abrir página de download",
        ["update.installing"] = "A iniciar o instalador… a app vai fechar.",

        // generic paid/quota connector confirmation
        ["dlg.cost.title"] = "Pesquisar com conectores pagos?",
        ["dlg.cost.body"] = "Tens conectores com custo/quota ligados (Apify e/ou JSearch). Esta pesquisa pode consumir créditos ou quota. Continuar?",
        ["settings.saved"] = "Definições guardadas.",

        // results titles + status (set in code)
        ["title.jobs"] = "Vagas para ti",
        ["title.demo"] = "Vagas para ti (demo)",
        ["title.saved"] = "Vagas guardadas",
        ["scoring.loadingSaved"] = "A carregar vagas guardadas…",
        ["scoring.loadingDemo"] = "A carregar demonstração…",
        ["scoring.searching"] = "A procurar vagas…",
        ["scoring.with"] = "A pontuar {0} candidatas com {1}…",
        ["scoring.rescoring"] = "A reclassificar com o modelo atual…",
        ["engine.claude"] = "o Claude CLI",
        ["engine.local"] = "o modelo local ({0})",
        ["pipe.demoLoading"] = "A carregar dados de demonstração (sem chamadas a IA)…",
        ["pipe.demoLoaded"] = "Demo: {0} vagas carregadas.",
        ["pipe.fetching"] = "A procurar vagas nas fontes…",
        ["pipe.collected"] = "{0} vagas recolhidas.",
        ["pipe.rescoring"] = "A reclassificar {0} vagas com o modelo atual…",
        ["pipe.fetcherMissing"] = "Fetcher não encontrado — a usar o jobs.raw.json existente, se houver.",
        ["empty.noSaved"] = "Ainda não há vagas guardadas — usa \"Procurar vagas\".",
        ["empty.noSavedRescore"] = "Sem vagas guardadas — usa \"Procurar vagas\" primeiro.",
        ["empty.noMatch"] = "Nenhuma vaga corresponde à pesquisa/filtros.",
        ["empty.noneToShow"] = "Sem vagas para mostrar. Usa “Procurar vagas” para fazer um varrimento, ou “Ver vagas” para as guardadas.",
        ["error.generic"] = "Erro: {0}",
        ["demo.profile.status"] = "Perfil de exemplo (John Doe) — experimenta a pesquisa. Não substitui o teu perfil guardado.",
        ["cv.reading"] = "A ler o CV…",
        ["cv.building"] = "A IA está a montar o teu perfil…",
        ["apify.validating"] = "A validar o token e a procurar actors…",
        ["models.loading"] = "A obter modelos do runtime local…",
        ["models.none"] = "Sem modelos — o runtime local está a correr no Base URL indicado?",

        // improve status
        ["plan.preparing"] = "A preparar a pesquisa…",
        ["plan.mapping"] = "A mapear o mercado para o teu perfil…",
        ["plan.deepening"] = "A identificar áreas a aprofundar…",
        ["plan.searching"] = "A pesquisar: {0}",
        ["plan.synth"] = "A sintetizar o teu plano de carreira…",
        ["plan.reuseResearch"] = "A reutilizar pesquisa recente…",
        ["plan.noModel"] = "O modelo não respondeu",
        ["plan.error.insufficient"] = "Não consegui reunir informação suficiente. Tenta outra vez.",

        // apify dialog
        ["dlg.apify.title"] = "Pesquisar com Apify (LinkedIn)?",
        ["dlg.apify.body"] = "O Apify é pago — esta pesquisa vai consumir créditos da tua conta Apify. Continuar?",
        ["dlg.continue"] = "Continuar",
        ["dlg.cancel"] = "Cancelar",

        // option labels
        ["opt.theme.system"] = "Sistema",
        ["opt.theme.light"] = "Claro",
        ["opt.theme.dark"] = "Escuro",
        ["opt.size.small"] = "Pequeno",
        ["opt.size.normal"] = "Normal",
        ["opt.size.large"] = "Grande",
        ["opt.size.larger"] = "Maior",
        ["opt.size.custom"] = "Personalizado",
        ["opt.lang.auto"] = "Automático",
        ["opt.field.desc"] = "Descrição",
        ["opt.field.title"] = "Título",
        ["opt.field.company"] = "Empresa",
        ["opt.field.location"] = "Localização",
        ["opt.field.source"] = "Fonte",
        ["opt.mode.contains"] = "contém",
        ["opt.mode.notcontains"] = "não contém",

        // language for AI prompts (used inside prompt text)
        ["ai.lang"] = "European Portuguese",
    };

    public static readonly Dictionary<string, string> En = new()
    {
        ["nav.home"] = "Home",
        ["nav.profile"] = "Profile",
        ["nav.jobs"] = "Jobs",
        ["nav.improve"] = "Grow",
        ["nav.settings"] = "Settings",
        ["theme.toggle"] = "Theme: {0}",

        ["home.tagline"] = "Point your CV at the job market — the AI builds your profile and we find the jobs that fit, scored and explained. All local, with your Claude CLI or a local model (BYOK).",
        ["home.search"] = "Search jobs",
        ["home.search.tip"] = "Fetch from sources and score again",
        ["home.viewJobs"] = "View jobs",
        ["home.viewJobs.tip"] = "Show the jobs already saved, without a new search",
        ["home.editProfile"] = "View / edit profile",
        ["home.loadOtherCv"] = "Load another CV",
        ["home.firstTitle"] = "Start with your CV",
        ["home.firstSub"] = "A text PDF. The AI extracts your profile and you confirm before searching.",
        ["home.pickCv"] = "Choose CV (PDF)…",
        ["home.demoCv"] = "Use sample CV",
        ["home.demoCv.tip"] = "Loads the sample profile (John Doe) — no tokens, doesn't touch your own profile.",
        ["home.demoRun"] = "See demo (no AI)",
        ["home.privacy"] = "Private and local. Reading the CV and scoring use your Claude CLI or a local model (BYOK) — nothing is sent to servers. The demo and the sample CV don't spend tokens.",

        ["profile.title"] = "Your profile",
        ["profile.sub"] = "Confirm what the AI extracted and fill in what a CV doesn't say.",
        ["profile.name"] = "NAME",
        ["profile.field"] = "FIELD / PROFESSION",
        ["profile.field.wm"] = "Software Engineering, Nursing, Accounting…",
        ["profile.titles"] = "JOB TITLES (search, comma-separated)",
        ["profile.titles.wm"] = "Backend Developer, Software Engineer",
        ["profile.coreSkills"] = "CORE SKILLS (comma-separated)",
        ["profile.otherSkills"] = "OTHER SKILLS",
        ["profile.locations"] = "LOCATIONS",
        ["profile.years"] = "YEARS OF EXPERIENCE",
        ["profile.seniority"] = "TARGET LEVEL",
        ["profile.salary"] = "SALARY €/YEAR (min / target)",
        ["profile.salary.min"] = "minimum",
        ["profile.salary.target"] = "target",
        ["profile.workmode"] = "WORK MODE",
        ["profile.remote"] = "Remote",
        ["profile.hybrid"] = "Hybrid",
        ["profile.onsite"] = "On-site",
        ["profile.summary"] = "SUMMARY",
        ["profile.classification"] = "SCORING",
        ["profile.classHint"] = "AI = 0–100 with reasoning. Keywords = fast, no AI.",
        ["profile.genCv"] = "Generate CV (PDF)",
        ["profile.genCv.tip"] = "Generate a PDF CV from this profile",
        ["profile.reset"] = "Start over",

        ["results.of"] = " of ",
        ["results.search.wm"] = "Search the jobs…",
        ["results.filter"] = "Filter",
        ["results.filter.tip"] = "Add a filter (e.g. description contains C#)",
        ["results.minScore"] = "Min. score",
        ["results.rescore"] = "Re-score",
        ["results.rescore.tip"] = "Score again with the engine from Settings",
        ["results.export"] = "Export",
        ["results.linkedin.tip"] = "Open LinkedIn Jobs with your search",
        ["filter.remove.tip"] = "Remove filter",
        ["results.howScore"] = "How is the score calculated?",
        ["results.howScore.body"] = "1) A keyword filter from your profile gives a pre-score (core skills, work mode, location, salary). 2) In AI mode, the best ones are scored 0–100 by the model, with a verdict, reasons and red flags. Open each job for the exact logic; click the title to open the listing.",
        ["job.openTip"] = "Open the listing",
        ["job.why"] = "Why this score",
        ["job.openJob"] = "Open job",
        ["job.research"] = "Research company",
        ["job.research.tip"] = "Searches the web for reviews and comparable salaries and summarises with your model",
        ["job.researching"] = "Researching the company…",
        ["brief.reputation"] = "REPUTATION",
        ["brief.salary"] = "SALARY",
        ["brief.expectation"] = "SALARY EXPECTATION FOR YOU",
        ["common.sources"] = "SOURCES",

        ["improve.sub"] = "A career plan from your profile and the market the radar has already seen — with research and sources.",
        ["improve.intro"] = "The Radar researches in-demand skills, salary trajectory and hiring trends for your field, cross-references everything with your profile and the jobs already scored, and returns strengths, gaps to close, target roles and next steps — with sources.",
        ["improve.generate"] = "Generate career plan",
        ["improve.byok"] = "Uses your AI engine (Claude CLI or local model) + key-free web search. Doesn't spend paid credits.",
        ["improve.positioning"] = "YOUR POSITIONING",
        ["improve.regenerate"] = "Regenerate",
        ["improve.regenerate.tip"] = "Research and regenerate the plan.",
        ["improve.strengths"] = "STRENGTHS",
        ["improve.gaps"] = "GAPS TO CLOSE",
        ["improve.roles"] = "TARGET ROLES",
        ["improve.salaryTraj"] = "SALARY TRAJECTORY",
        ["improve.now"] = "NOW",
        ["improve.potential"] = "POTENTIAL · 12–24 MONTHS",
        ["improve.steps"] = "NEXT STEPS",
        ["improve.signals"] = "MARKET SIGNALS",

        ["settings.sub"] = "Appearance and the AI engine used to read the CV and score the jobs.",
        ["settings.appearance"] = "APPEARANCE",
        ["settings.appearance.hint"] = "Light, dark or follow the system.",
        ["settings.textsize"] = "TEXT SIZE",
        ["settings.textsize.hint"] = "Scales the whole app. Also Ctrl +/− · Ctrl 0 · Ctrl+mouse wheel.",
        ["settings.language"] = "LANGUAGE",
        ["settings.language.hint"] = "Application language.",
        ["settings.aiEngine"] = "AI ENGINE",
        ["settings.aiEngine.hint"] = "Claude CLI uses your subscription (BYOK). Local model uses an OpenAI-compatible runtime (LM Studio, Ollama, llama.cpp) — runs offline, no subscription.",
        ["settings.localModel"] = "Local model",
        ["settings.presets"] = "Presets:",
        ["settings.apiKey"] = "API KEY (optional)",
        ["settings.claudeExe"] = "CLAUDE EXECUTABLE (PATH)",
        ["settings.model"] = "MODEL",
        ["settings.load"] = "Load",
        ["settings.model.hint"] = "Loads the list from the local runtime (it must be running at the Base URL).",
        ["settings.on"] = "On",
        ["settings.off"] = "Off",
        ["settings.apify.warnBold"] = "Heads up — costs: ",
        ["settings.apify.warn"] = "Apify is paid and each search consumes credits from your Apify account. With Apify on, the app always asks for confirmation before searching.",
        ["settings.apify.test"] = "Test / search",
        ["settings.apify.test.tip"] = "Validates the token (free, no credits) and searches for LinkedIn actors",
        ["settings.apify.max"] = "MAX RESULTS (caps the cost)",
        ["settings.apify.hint"] = "Paste the token (apify.com → Settings → API) and click “Test / search”. Validating and listing is free; only the search itself spends credits.",
        ["settings.save"] = "Save",

        // JSearch connector
        ["settings.jsearch"] = "JSEARCH (RAPIDAPI)",
        ["settings.jsearch.key"] = "RAPIDAPI KEY",
        ["settings.jsearch.max"] = "MAX RESULTS",
        ["settings.jsearch.warn"] = "JSearch (RapidAPI) has a free tier with a monthly request limit. With JSearch on, the app asks for confirmation before searching.",
        ["settings.jsearch.hint"] = "Create a RapidAPI account, subscribe to JSearch and copy your X-RapidAPI-Key.",
        ["jsearch.fetching"] = "Fetching jobs from JSearch (RapidAPI)…",
        ["jsearch.count"] = "JSearch: {0} jobs.",
        ["jsearch.failed"] = "JSearch failed (HTTP {0}) — check the RapidAPI key.",
        ["jsearch.error"] = "JSearch: error — {0}",

        // local model download (Ollama)
        ["settings.downloadModel"] = "DOWNLOAD MODEL (OLLAMA)",
        ["settings.downloadModel.wm"] = "e.g. llama3.2",
        ["settings.download"] = "Download",
        ["settings.downloadModel.hint"] = "Downloads a model via Ollama (it must be running at the Base URL). LM Studio: use the LM Studio app.",
        ["models.pulling"] = "Downloading {0} — {1}",
        ["models.pullDone"] = "{0} downloaded.",
        ["models.pullFail"] = "Download failed — is Ollama running at the Base URL?",
        ["models.section"] = "LOCAL MODELS (OLLAMA)",
        ["models.none"] = "No models yet. Install one below (suggested) or type a name.",
        ["models.unreachable"] = "Ollama isn't responding. Install it and keep it running.",
        ["models.active"] = "active",
        ["models.install"] = "Install a model",
        ["models.suggested"] = "Suggested",
        ["models.refresh"] = "Refresh",
        ["models.remove"] = "Remove",
        ["models.remove.tip"] = "Remove model",
        ["models.removeConfirm"] = "Remove {0}?",
        ["models.removeBody"] = "The model will be deleted from your disk.",
        ["models.getOllama"] = "Install Ollama",
        ["models.setActive.tip"] = "Use this model",
        ["connector.free"] = "Free",
        ["connector.paid"] = "Paid",
        ["connector.getKey"] = "Get key →",
        ["settings.advanced"] = "ADVANCED",
        ["research.noWeb"] = "No web-search results (it may be throttled — try again).",
        ["research.noModel"] = "The model didn't respond",
        ["research.failed"] = "Company research failed.",
        ["usage.section"] = "USAGE & LIMITS",
        ["usage.refresh"] = "Refresh",
        ["usage.hint"] = "Limits of the paid/quota APIs. Your Claude/local model isn't metered here.",
        ["usage.jsearch"] = "{0} of {1} requests left this month",
        ["usage.jsearch.none"] = "run a JSearch query to see the quota",
        ["usage.claude"] = "subscription (not metered here) — if you hit the limit, search/scoring fails",
        ["usage.local"] = "local — no limits",
        ["usage.unknown"] = "—",

        // sources & keys setup guide
        ["settings.sources"] = "SOURCES & KEYS",
        ["setup.jsearch"] = "JSearch (RapidAPI) — job aggregator. Subscribe and copy the X-RapidAPI-Key.",
        ["setup.apify"] = "Apify — LinkedIn connector (paid). Create an API token.",
        ["setup.ollama"] = "Ollama — local models. Install and download models.",
        ["setup.lmstudio"] = "LM Studio — local models with a GUI.",
        ["setup.open"] = "Open",
        ["setup.library"] = "Models",

        // about / update
        ["settings.about"] = "ABOUT",
        ["settings.version"] = "Version {0}",
        ["settings.checkUpdate"] = "Check for updates",
        ["update.checking"] = "Checking for updates…",
        ["update.upToDate"] = "You're on the latest version ({0}).",
        ["update.available"] = "New version available: {0}",
        ["update.downloading"] = "Downloading update — {0}",
        ["update.failed"] = "Couldn't check/download. Try the download page.",
        ["update.openPage"] = "Open download page",
        ["update.installing"] = "Starting the installer… the app will close.",

        // generic paid/quota connector confirmation
        ["dlg.cost.title"] = "Search with paid connectors?",
        ["dlg.cost.body"] = "You have cost/quota connectors enabled (Apify and/or JSearch). This search may consume credits or quota. Continue?",
        ["settings.saved"] = "Settings saved.",

        ["title.jobs"] = "Jobs for you",
        ["title.demo"] = "Jobs for you (demo)",
        ["title.saved"] = "Saved jobs",
        ["scoring.loadingSaved"] = "Loading saved jobs…",
        ["scoring.loadingDemo"] = "Loading demo…",
        ["scoring.searching"] = "Searching for jobs…",
        ["scoring.with"] = "Scoring {0} candidates with {1}…",
        ["scoring.rescoring"] = "Re-scoring with the current engine…",
        ["engine.claude"] = "the Claude CLI",
        ["engine.local"] = "the local model ({0})",
        ["pipe.demoLoading"] = "Loading demo data (no AI calls)…",
        ["pipe.demoLoaded"] = "Demo: {0} jobs loaded.",
        ["pipe.fetching"] = "Searching the sources for jobs…",
        ["pipe.collected"] = "{0} jobs collected.",
        ["pipe.rescoring"] = "Re-scoring {0} jobs with the current engine…",
        ["pipe.fetcherMissing"] = "Fetcher not found — using the existing jobs.raw.json, if any.",
        ["empty.noSaved"] = "No saved jobs yet — use \"Search jobs\".",
        ["empty.noSavedRescore"] = "No saved jobs — use \"Search jobs\" first.",
        ["empty.noMatch"] = "No jobs match the search/filters.",
        ["empty.noneToShow"] = "No jobs to show. Use “Search jobs” to run a scan, or “View jobs” for the saved ones.",
        ["error.generic"] = "Error: {0}",
        ["demo.profile.status"] = "Sample profile (John Doe) — try the search. It doesn't replace your saved profile.",
        ["cv.reading"] = "Reading the CV…",
        ["cv.building"] = "The AI is building your profile…",
        ["apify.validating"] = "Validating the token and searching for actors…",
        ["models.loading"] = "Fetching models from the local runtime…",
        ["models.none"] = "No models — is the local runtime running at the Base URL?",

        ["plan.preparing"] = "Preparing the research…",
        ["plan.mapping"] = "Mapping the market for your profile…",
        ["plan.deepening"] = "Identifying areas to dig into…",
        ["plan.searching"] = "Searching: {0}",
        ["plan.synth"] = "Synthesising your career plan…",
        ["plan.reuseResearch"] = "Reusing recent research…",
        ["plan.noModel"] = "The model didn't respond",
        ["plan.error.insufficient"] = "Couldn't gather enough information. Try again.",

        ["dlg.apify.title"] = "Search with Apify (LinkedIn)?",
        ["dlg.apify.body"] = "Apify is paid — this search will consume credits from your Apify account. Continue?",
        ["dlg.continue"] = "Continue",
        ["dlg.cancel"] = "Cancel",

        ["opt.theme.system"] = "System",
        ["opt.theme.light"] = "Light",
        ["opt.theme.dark"] = "Dark",
        ["opt.size.small"] = "Small",
        ["opt.size.normal"] = "Normal",
        ["opt.size.large"] = "Large",
        ["opt.size.larger"] = "Larger",
        ["opt.size.custom"] = "Custom",
        ["opt.lang.auto"] = "Automatic",
        ["opt.field.desc"] = "Description",
        ["opt.field.title"] = "Title",
        ["opt.field.company"] = "Company",
        ["opt.field.location"] = "Location",
        ["opt.field.source"] = "Source",
        ["opt.mode.contains"] = "contains",
        ["opt.mode.notcontains"] = "doesn't contain",

        ["ai.lang"] = "English",
    };
}
